### ISSUE TITLE
Support of the IBM Power9 (ppc64le) architecture

### ISSUE THREAD

**Issue by raimis** [conda-forge/plumed-feedstock#22]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Is any plan to support the IBM Power9 (`ppc64le`) architecture? It was reported that the code compiles and pass the majority of the tests: https://github.com/plumed/plumed2/issues/569

OpenMM has just been ported to `ppc64le` (https://github.com/conda-forge/openmm-feedstock/pull/55), so it would be good to have PLUMED too.

**Comment by awvwgk** [comment]
Currently waiting for https://github.com/conda-forge/vim-feedstock/pull/1224 to get merged, since vim is a build requirement.

**Comment by GiovanniBussi** [comment]
@raimis @awvwgk I actually made a change on plumed master branch so that vim won't be anymore a build requirement. It will be included in plumed v2.8.

It's actually a [single commit](https://github.com/plumed/plumed2/commit/e84a4aee8a997952866303b080d5f50058645593) that could be backported. If there's any volunteer to create a patch for the conda build (I don't know how to do it), so that this commit is applied on v2.7 before building it, I would be happy to merge it in the feedstock. Otherwise I would wait for vim to get merged.

**Comment by awvwgk** [comment]
You can just add the patch to the recipe directory (https://github.com/plumed/plumed2/commit/e84a4aee8a997952866303b080d5f50058645593.patch as new file) and apply it to the downloaded source in the `recipe/meta.yaml` with:

```yaml
source:
  url: https://github.com/plumed/plumed2/archive/v{{ version }}.tar.gz
  sha256: cb8b5735d8dd61980fa6441f3dde3f33544240ae4177da0f529fb5abb355cd4a
  patches:
    - remove-xxd-dep.patch
```

It is also quite straight-forward to add the architectures yourself in `conda-forge.yml` and rerender the feedstock:

```yaml
provider:
  linux_aarch64: default    
  linux_ppc64le: default
```
